### ISSUE TITLE
`yarn start` doesn't work? 

### ISSUE THREAD

**Issue by kassens** [relayjs/relay-examples#101]
moved from https://github.com/facebook/relay/issues/2836

**Comment by kassens** [comment]
Seems to work for me, also on a macbook.

<img width="436" alt="image" src="https://user-images.githubusercontent.com/11849/64263145-30115200-cefd-11e9-9dba-9bbd2226e237.png">


Can you check you're on master @j4nos?

**Comment by tyao1** [comment]
Also works for me on a macbook.
