### ISSUE TITLE
exceeds the max of "100KB" run on react native

### ISSUE THREAD

**Issue by yutin1987** [relayjs/relay-examples#11]
Note: The code generator has deoptimised the styling of "/Users/yutin/Develop/github/relay-examples/TodoMVC/node_modules/immutable/dist/immutable.js" as it exceeds the max of "100KB"

![image](https://cloud.githubusercontent.com/assets/2505934/19600781/1b150602-97d9-11e6-88ce-2da3266a9df1.png)

```


    "amdefine": ">=0.0.4",
    "babel-preset-react-native": "1.9.0",
    "babel-relay-plugin": "0.9.2",
    "express": "4.13.4",
    "express-graphql": "0.5.2",
    "graphql": "0.6.0",
    "graphql-relay": "0.4.2",
    "react": "15.1.0",
    "react-native": "0.28.0",
    "react-native-listitem": "1.0.5",
    "react-relay": "0.9.2",
    "babel-cli": "6.9.0",
    "babel-core": "6.9.1"
```

**Comment by kassens** [comment]
We need to fully update the React Native example since it's using a really old version. Closing in favor of #53.
