### ISSUE TITLE
Watchman dependency not mentioned in README

### ISSUE THREAD

**Issue by matthewbryancurtis** [relayjs/relay-examples#117]
This might be related to:
- https://github.com/relayjs/relay-examples/issues/91
- https://github.com/relayjs/relay-examples/issues/23

When trying to run the Issue-Tracker example, I'm getting an error when running `yarn start`:

```
$ yarn run relay-compiler --schema schema/schema.graphql --src ./src/ $@ --watch
$ /Users/[[PATH]]/relay-examples/issue-tracker/node_modules/.bin/relay-compiler --schema schema/schema.graphql --src ./src/ --watch
[relay] Error: Watchman is required to watch for changes.
```

I imagine that the example requires a global Watchman dependency? Or is this a bug with relay? Is it the `watchman` or `fb-watchman` package in npm? Maybe this would be a good candidate for a dev dependency?

Any advice would be appreciated and might make a good addition to the README. Would be glad to submit a PR when I find out what to do.

**Comment by josephsavona** [comment]
Thanks for filing. We've updated Relay compiler to warn if watch mode is used w/o watchman being installed, this change will go out w the next release.
