### ISSUE TITLE
issue-tracker demo is error

### ISSUE THREAD

**Issue by xuanlongvts** [relayjs/relay-examples#123]
<img width="1254" alt="Screen Shot 2019-11-16 at 3 23 04 PM" src="https://user-images.githubusercontent.com/11780302/68990391-17220700-0885-11ea-82b8-c79e8e5e44cf.png">

As image above, Watchman is required to watch for changes.

**Comment by kakas** [comment]
install watchman by `brew install watchman`

OR
change `package.json` 

```diff
-    "start": "yarn run relay; concurrently --kill-others --names \"react-scripts,relay\" \"react-scripts start\" \"yarn run relay --watch\"",
+    "start": "yarn run relay && react-scripts start",
```

**Comment by xuanlongvts** [comment]
Thanks! It works for me.
