### ISSUE TITLE
_cacheConfig isn't being used on RelayEnvironment.js

### ISSUE THREAD

**Issue by jgcmarins** [relayjs/relay-examples#125]
Hello everyone! Great job here, thanks for sharing all this content!

Is there any reason why `_cacheConfig` is being passed as parameter, but not being used?

https://github.com/relayjs/relay-examples/blob/c42500546d3ff8dedc8fabc4910e2a54334b6419/issue-tracker/src/RelayEnvironment.js#L8

**Comment by voideanvalue** [comment]
`cacheConfig` is passed when relay invokes this function but this implementation doesn't use it. `_variableName` is a convention for unused parameters. we could skip it from the function signature altogether too.

https://github.com/facebook/relay/blob/d8530106d08c90d3d7be6e79aeda9692edf688e5/packages/relay-runtime/network/RelayNetworkTypes.js#L98-L110
