### ISSUE TITLE
preloadQuery(): Expected a RelayModernEnvironment

### ISSUE THREAD

**Issue by PatoBeltran** [relayjs/relay-examples#128]
I just followed the instructions set in the readme to start out trying the issue tracker repo, after I do npm start I get the browser open with an error:

```
preloadQuery(): Expected a RelayModernEnvironment
```

**Comment by sibelius** [comment]
make sure all relay version match

```
yarn why react-relay
yarn why relay-runtime
yarn why relay-compiler
yarn why babel-plugin-relay
```

**Comment by josephsavona** [comment]
Thanks for reporting this. Depending on the  order in which you install things it's possible to end up with multiple versions of relay-runtime. I would try uninstalling relay-runtime and make sure you  only have one copy. We'll also look at updating  the instructions to try and avoid this - w're also open to contributions to update the readme too!

**Comment by PatoBeltran** [comment]
I have the following versions:

```
    "react": "0.0.0-experimental-b53ea6ca0",
    "react-dom": "0.0.0-experimental-b53ea6ca0",
    "react-markdown": "^4.2.2",
    "react-relay": "^0.0.0-experimental-a1a40b68",
    "react-router": "^5.1.2",
    "react-router-config": "^5.1.1",
    "react-scripts": "3.2.0",
    "relay-runtime": "^7.0.0"
```

Since I just ran `npm install` once I cloned the repo I'm not sure which order the dependencies where resolved. What is the appropriate order I have to follow to get the correct `relay-runtime`?

**Comment by sibelius** [comment]
Remove relay repo runtime

**Comment by PatoBeltran** [comment]
I was able to fix this by removing the carets on all versions to make sure everything is loaded with the same version (7.0.0), I also updated the scripts to run. Would you like me to send a PR with this updates so that the out-of-the-box version of this repo works?

**Comment by PatoBeltran** [comment]
here is the PR with this fix https://github.com/relayjs/relay-examples/pull/129
