### ISSUE TITLE
Circular dependency between node and types

### ISSUE THREAD

**Issue by MoeSattler** [relayjs/relay-examples#13]
I think it's odd that we have that kind of circular dependencies between the [types](https://github.com/relayjs/relay-examples/blob/master/star-wars/data/schema.js#L159) and the [node](https://github.com/relayjs/relay-examples/blob/master/star-wars/data/schema.js#L136).
This makes it impossible to put types in own files an clean up code. Is there currently a way to avoid that?

**Comment by yuzhi** [comment]
Node is an interface/type. What did you mean by circular dependency here?

**Comment by eladams** [comment]
This is/can be resolved by:
`interfaces: () => [NodeInterface]`
Hope this helps.

**Comment by MoeSattler** [comment]
@eladams thanks!
