### ISSUE TITLE
viewer type pattern removed, but tutorial not updated

### ISSUE THREAD

**Issue by jtonneyck** [relayjs/relay-examples#130]
The viewer type pattern was removed in https://github.com/relayjs/relay-examples/pull/62, but the tutorial on the graphql website wasn't updated (https://relay.dev/docs/en/quick-start-guide). This is super confusing for beginners.

**Comment by sibelius** [comment]
care to send a pull request on facebook/relay improving the docs?

**Comment by Piepongwong** [comment]
I would like to, but I feel like I need to understand Relay more before I suggest an improvement. I'll get back to this in +/- a week.

**Comment by daig** [comment]
Any progress on this? It's been a long time for the quickstart to be broken, do people still use Relay?

**Comment by sibelius** [comment]
more and more people are using Relay (Facebook, Twitter, Hasura is bringing support to it)
I'm gonna give a workshop about Relay new features at React Europe, check the demo here https://twitter.com/ReactEurope/status/1226951417002446849

feel free to send a pull request to fix this

**Comment by voideanvalue** [comment]
Closing this as the quick-start-guide no longer references `viewer`
