### ISSUE TITLE
Remove ViewerType pattern from Relay Modern example

### ISSUE THREAD

**Issue by robrobkay51** [relayjs/relay-examples#14]
I recently came across this comment by Lee Byron which advises against using the Viewer type pattern in GraphQL/Relay applications: https://github.com/lucasbento/graphql-pokemon/issues/1#issuecomment-258932874 

If this is now considered best practice, it would be helpful if all examples within this Repo were updated to reflect the guidelines outlined in the above issue thread.

**Comment by wincent** [comment]
Thanks for the suggestion, but I don't think we should consider doing this until the new Relay core is out (which has much less hacky support for the `Viewer` type, and drops existing restrictions around root fields). While it's true that `Viewer` is somewhat of a Facebook-ism, that doesn't necessarily make it an anti-pattern (I think Lee's language is a bit to strong there); it's a convention that has served us well, is perhaps a bit quirky, and one which perhaps we wouldn't have encouraged if we could go back a few years and design the system from scratch. For a related comment I just made on this, [see here](https://github.com/facebook/relay/issues/1542#issuecomment-279123639).

Having said all that, I am totally happy to remove `Viewer` from the examples. But let's wait until the new core and APIs are fully rolled out.

**Comment by ardalann** [comment]
@wincent @leebyron Now that Relay Modern is out, is there an example of this?
The TodoModern example still uses the Viewer field: 
https://github.com/relayjs/relay-examples/blob/master/todo-modern/data/schema.js

**Comment by wincent** [comment]
It would be fine to remove the `Viewer` type from the modern example if you wanted to. There is no "official" example of making that kind of change yet (if there was, it would be here); for an unofficial example, [here's the commit](https://github.com/wincent/masochist/commit/637d0184f3318370b9ebc5285535e49) in my blog repo where I got rid of the `User` and `Viewer` types once I'd moved to Relay Modern.

Adding a "help wanted" label in case anybody wants to take a stab at this.

**Comment by fernandocalsa** [comment]
Is this issue still relevant? I'm starting with Relay Modern and I would like to help on this issue, I think it can help me to understand better the framework. I've never worked with GraphQL before so I don't know about Relay Classic. @wincent do you think a beginner can fix this issue?

**Comment by sibelius** [comment]
you can check this 2 pull requests

https://twitter.com/sseraphini/status/900775274387820544

https://github.com/entria/graphql-dataloader-boilerplate/pull/59
https://github.com/entria/ReactNavigationRelayModern/pull/18

**Comment by fernandocalsa** [comment]
thank you @sibelius I will try to work on it whenever I have some time :D

**Comment by Stephen2** [comment]
#88 closes this
