### ISSUE TITLE
`react-router` preloading

### ISSUE THREAD

**Issue by unindented** [relayjs/relay-examples#145]
In the `issue-tracker` example, you say:

> React Router does not yet support preloading data for routes (the React Router team is working on this)

Do you know for a fact that they're working on it? I don't see it in their roadmap: https://github.com/ReactTraining/react-router/issues/6885

**Comment by dohaicuong** [comment]
I found something on that
https://github.com/ReactTraining/react-router/issues/7200
it's on react router v6, released beta version yesterday

**Comment by unindented** [comment]
Ah awesome, thanks for the update! Feel free to close then.
