### ISSUE TITLE
a bug in treasurehunt

### ISSUE THREAD

**Issue by 0rangeT1ger** [relayjs/relay-examples#15]
in `database.js`
```
export function getHidingSpot(id) {
  return hidingSpots.find(hs => hs.id === id)
}
```
if I add log here: 
```
console.log(`id: ${id}  ${hs.id}  ${hs.id === id} ${hs.id == id}`)
```
if the id is '2', it will print： 'id: 2 2 false true'

Am I making a mistake or maybe it shouldn't be `===` but `==` in the `getHidingSpot` function?

**Comment by pranaygp** [comment]
Thanks for reporting this @0rangeT1ger 😃 

I tried what you suggested on the the current master and got this:

```
id: 2  2  true true
```

Seems like it has been fixed since you reported it 🎉
