### ISSUE TITLE
Is nested routes supported or not?

### ISSUE THREAD

**Issue by hegelstad** [relayjs/relay-examples#159]
There is a merged pull request #109 that adds nested routes, and there is also this sentence in the documentation that says nested routes is not implemented yet in this example:

https://github.com/relayjs/relay-examples/blob/e77b3d1f15e4b5c5bb29ebe76a3ed9cc73fc9484/issue-tracker/src/routes.js#L34-L36

Which is true?

**Comment by sibelius** [comment]
It works

Check relay-workshop for another example
