### ISSUE TITLE
Migrate todo-modern off Relay Compat

### ISSUE THREAD

**Issue by kmjennison** [relayjs/relay-examples#21]
The todo-modern example is running Relay Compat, which can be confusing when using it as a reference for writing a Relay Modern app (e.g. fragment syntax differences). It would be helpful to either note in the readme that it's running compatibility mode or migrate it to pure Relay Modern.

**Comment by kassens** [comment]
cc @alangenfeld I think you had intentions to show this as a way to migrate? If that's the case we could fork the directory into todo-compat and todo-modern.

**Comment by alangenfeld** [comment]
Yep, the plan is to complete the migration all the way to modern, and be able to point at the history as an example of how to incrementally migrate. Should have some time to progress it forward this week.

**Comment by tjmehta** [comment]
The history idea is nice, but would be useful to see a full relay-modern example application (for those writing new applications). I haven't been able to find any good ones w/ (mutations, etc) on the web.

**Comment by alangenfeld** [comment]
now it is fully upgraded with working optimistic mutations
