### ISSUE TITLE
[todo-modern] Error: Watchman was not found in PATH.

### ISSUE THREAD

**Issue by ltlam93** [relayjs/relay-examples#23]
> relay-compiler --src ./js/ --schema ./data/schema.graphql

HINT: pass --watch to keep watching for changes.
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

npm ERR! Linux 4.10.0-19-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `relay-compiler --src ./js/ --schema ./data/schema.graphql`
npm ERR! Exit status 1

**Comment by jonirrings** [comment]
you should install watchman first and make sure it is in `path`
under macOS, watchman works fine, but under windows, the `__generated__` dirs were not generated.

**Comment by iamglenbacs** [comment]
so do we fix it on windows

**Comment by jonirrings** [comment]
hi, @iamglenbacs ,do you succeed building the _generated_/ dirs? I've failed:fearful:, what your config if success. i only puth the `watchman.exe` in `path`.

**Comment by taven-liu** [comment]
I also get the same problem, even though I've installed `watchman` and added path

**Comment by brysgo** [comment]
This dependency is a bit of a pain for me on ci as well.

**Comment by taven-liu** [comment]
now, i use `yarn` reinstall the `node_modules` and then the project can running normally.

**Comment by wincent** [comment]
Also see https://github.com/facebook/relay/issues/1644 — I'd like to see us gracefully fallback to a non-watchman implementation when Watchman is not available (and especially when not running under `--watch` mode).

**Comment by wincent** [comment]
But note, I don't think this is an issue with the examples; we should improve this in Relay itself, so I'm going to close this one. Thanks for the input, and if you'd like to continue to discuss this let's do it on the Relay issue tracker (probably on the issue that I just linked to in my previous comment, at least to start with).
