### ISSUE TITLE
[relay-examples/todo]Root.node field type must be Output Type but got: Node.

### ISSUE THREAD

**Issue by jonirrings** [relayjs/relay-examples#25]
just run
```
cd relay-examples/todo
yarn
yarn upgrade graphql graphql-relay
yarn run update-schema
```
then comes this error
```
D:\CodeToRead\relay-examples\todo>yarn run update-schema
yarn run v0.23.2
$ babel-node ./scripts/updateSchema.js
D:\CodeToRead\relay-examples\todo\node_modules\graphql\jsutils\invariant.js:19
    throw new Error(message);
    ^

Error: Root.node field type must be Output Type but got: Node.
    at invariant (D:\CodeToRead\relay-examples\todo\node_modules\graphql\jsutils\invariant.js:19:11)
    at D:\CodeToRead\relay-examples\todo\node_modules\graphql\type\definition.js:337:29
    at Array.forEach (native)
    at defineFieldMap (D:\CodeToRead\relay-examples\todo\node_modules\graphql\type\definition.js:328:14)
    at GraphQLObjectType.getFields (D:\CodeToRead\relay-examples\todo\node_modules\graphql\type\definition.js:282:44)
    at typeMapReducer (D:\CodeToRead\relay-examples\todo\node_modules\graphql\type\schema.js:206:25)
    at Array.reduce (native)
    at new GraphQLSchema (D:\CodeToRead\relay-examples\todo\node_modules\graphql\type\schema.js:95:34)
    at Object.<anonymous> (D:/CodeToRead/relay-examples/todo/data/schema.js:278:23)
    at Module._compile (module.js:571:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
the node version is `v7.9.0`
has anybody met this error? how to locate where the error occured?

**Comment by wincent** [comment]
Thanks @jonirrings!

I was going to say that it seems likely that this is a result of moving to v0.10.0 or v0.10.1 (the two latest versions at the time I write this) of the "graphql" NPM package, but I see you posted this 29 days ago and those only came out 6 and 5 days ago, respectively. Another possible suspect is https://github.com/graphql/graphql-js/pull/695, which first got released in v0.9.5 (on April 28).

I don't know what the problem is here, but it is *possible* that you have multiple conflicting versions of "graphql" in your "node_modules" folder, which could potentially cause any of a number of `instanceof` checks to fail, leading to the kind of invariant that you're seeing.

If you do do any further digging into this, please let us know what you find out.

**Comment by jonirrings** [comment]
hi, @wincent 
thanks for your reply

I solved similar problem (`Query.node field config must be an object`) in my project by 
and use 
```js
const { connectionType: UserConnection, edgeType: UserEdge } = connectionDefinitions({
  name: 'User',
  nodeType: UserType,
});
export { UserConnection, UserEdge };
```
instead of
```js
export const { connectionType: UserConnection, edgeType: UserEdge } = connectionDefinitions({
  name: 'User',
  nodeType: UserType,
});
```

I found this a syntax problem, that is the syntax `export const {xxx:A,yyy:B} = getObject` is not in the ES2015 spec (do I miss something?).


for this problem I've debugged and found something, but not sure if it is the cause, but it is like what you said.

the graphql-relay@0.5.2 will install a graphql@0.6.2 as peer-dependency in its node_modules, and the project itself will install a graphql@0.10.1 if upgraded or install without version number .

but installing both in correct squence will solve the problem
```
# UPGRADE
yarn remove graphql-relay
yarn upgrade graphql
yarn add graphql-relay
```
```
# INSTALL
yarn add graphql
yarn add graphql-relay
```
that seems that I'm not familiar with npm and nodejs module installation and resolution.

**Comment by wincent** [comment]
Thanks for reporting back. In general we can make this better by making sure we keep all of our "graphql"-using packages up to date on on the same version of "graphql". But even then, there will be brief windows, and user-specific installation/upgrade-ordering scenarios that can cause this kind of issue to surface. Would be nice to have a systematic way to prevent (or at least detect/alert), but I don't think we're there yet.

**Comment by AchrafBn** [comment]
After  installed `loopback-graphql-relay` and run my server, i have  the same error 
the node version is v8.3.0
Any idea ?

**Comment by jonirrings** [comment]
@AchrafBn check the peer dependency of `loopback-graphql-relay`, install that version of `graphql.js` and `relay`.
1.  check the peer dependency of `loopback-graphql-relay`
2.  install that version of `graphql.js`
3.  install that version of `relay.js`
4.  install `loopback-graphql-relay`

can this tackle with your problem ?

**Comment by AchrafBn** [comment]
@jonirrings 
loopback-graphql-relay : v0.9.3
graphql: v0.9.6
graphql-relay:v0.5.2
I tried with these versions, but got the same error.
