### ISSUE TITLE
FIXME at optimistic update

### ISSUE THREAD

**Issue by bsr203** [relayjs/relay-examples#3]
Hi,

there is a `FIXME` comment [here](https://github.com/relayjs/relay-examples/blob/master/TodoMVC/mutations/AddTodoMutation.js#L60) 

Is this still valid. If so, why only total count is updated but not the node/item?

**Comment by steveluscher** [comment]
Can you give it a shot for us? Use the Chrome debugger to slow down the connection and see if the optimistic update adds the edge as one would hope!

https://developer.chrome.com/devtools/docs/device-mode#network-conditions

**Comment by bsr203** [comment]
sure. will do shortly after 4th

**Comment by bsr203** [comment]
Hi @steveluscher

it works well by updating the total count as well as adding a todo item while the response is pending. I found that chrome network throttling doesn't work for ajax (it worked first on the app loading, but not subsequent graphql xhr calls) and set up a proxy to test this.

Also, if I click on the node which is created with optimistic payload, got this this error. kinda make sense but just FYI. 
```
app.js:1058 Uncaught Invariant Violation: RelayQueryPath.createForID: Expected dataID to be a server id, got `client:-5805023296`.invariant @ app.js:1058createForID @ app.js:24316mergeField @ app.js:38496handleMerge @ app.js:38465writeRelayUpdatePayload @ app.js:38383(instrumented writeRelayUpdatePayload) @ app.js:27566handleUpdatePayload @ app.js:22704(instrumented RelayStoreData.prototype.handleUpdatePayload) @ app.js:27566_handleOptimisticUpdate @ app.js:29347applyOptimistic @ app.js:29299applyOptimistic @ app.js:29742applyUpdate @ app.js:22366commitUpdate @ app.js:22376Todo._this._handleCompleteChange @ app.js:51778executeOnChange @ app.js:13392_handleChange @ app.js:13213ReactErrorUtils.invokeGuardedCallback @ app.js:6624executeDispatch @ app.js:6408executeDispatchesInOrder @ app.js:6431executeDispatchesAndRelease @ app.js:5875executeDispatchesAndReleaseTopLevel @ app.js:5886forEachAccumulated @ app.js:6725processEventQueue @ app.js:6048runEventQueueInBatch @ app.js:12842handleTopLevel @ app.js:12853handleTopLevelImpl @ app.js:17187perform @ app.js:8450batchedUpdates @ app.js:17104batchedUpdates @ app.js:7652dispatchEvent @ app.js:17264
```

**Comment by bsr203** [comment]
I am trying every avenue I can. could you please comment on https://github.com/facebook/relay/issues/487#issuecomment-232055346 . greatly appreciate it. thanks.
