### ISSUE TITLE
Relay modern with routing example

### ISSUE THREAD

**Issue by ilanbiala** [relayjs/relay-examples#31]
Is there an example app that uses Relay Modern with some sort of routing in between pages? If not, is there another repo where I can find something similar?

**Comment by johndanek** [comment]
I would also love a Relay Modern example that doesn't use a local database. I'm having a tough time adding React Modern to my project due to a lack of complete documentation or examples.

**Comment by taion** [comment]
See https://github.com/taion/relay-todomvc, specifically https://github.com/taion/relay-todomvc/tree/found-modern (Relay Modern) and https://github.com/taion/relay-todomvc/tree/found-modern-universal (Relay Modern + SSR).

**Comment by jonirrings** [comment]
thanks for the example, I'm searching a route library too.
previously used the `isomophic-relay-router`

**Comment by brysgo** [comment]
I think @taion was pointing at 'Found' as the route library. Also, I am using relay modern with react router 4 without issue. Granted the app I'm using it on isn't huge so there may be some hurdles with a large app.

**Comment by taion** [comment]
That's correct. Use Found. RRv4 doesn't give you a good way to handle nested queries.

**Comment by brysgo** [comment]
Could you elaborate on that, what is the issue you are thinking of?

**Comment by taion** [comment]
If you need to nest routes that require Relay data, with RRv4, you're stuck nesting `<QueryRenderer>`s, which (1) gives you request waterfalls and (2) doesn't easily allow SSR.

**Comment by brysgo** [comment]
Ah, I see. Yeah, my routes just end up looking like this:
```jsx
<Route
  path={"/nested/:thingId/thing"}
  component={props => <Thing data={data} {...props} />}
/>
```
And that is how I orchestrate my fragment containers.
