### ISSUE TITLE
Stuck at Loading ... todo-modern

### ISSUE THREAD

**Issue by CR1AT0RS** [relayjs/relay-examples#33]
Hi,

My app is stuck on loading . . No error in console.
<img width="1014" alt="screen shot 2017-06-23 at 9 02 45 pm" src="https://user-images.githubusercontent.com/4299288/27505561-5b272af6-5857-11e7-9737-2481292ad926.png">

Compiler successfully.  Need to change these package versions
"express-graphql": "^0.6.6",
    "graphql": "^0.10.3",
    "graphql-relay": "^0.5.1",

**Comment by marcosrmendezthd** [comment]
@CR1AT0RS I just ran into this and in my case there was something else listening on port 8080. So I'd suggest you check that.

If for some reason you can't stop whatever is listening on that port, you can just add the graphql endpoint to the app, as a workaround.

disable separate graphql server
```
// const GRAPHQL_PORT = 8080;

// Expose a GraphQL endpoint
// const graphQLServer = express();
// graphQLServer.use('/', graphQLHTTP({schema, pretty: true}));
// graphQLServer.listen(GRAPHQL_PORT, () => console.log(
//   `GraphQL Server is now running on http://localhost:${GRAPHQL_PORT}`
// ));
```

disable proxy
```
// proxy: {'/graphql': `http://localhost:${GRAPHQL_PORT}`},
```

add graphql endpoint to app

```app.use('/graphql', graphQLHTTP({schema, pretty: true}));```

**Comment by wincent** [comment]
I am going to (optimistically) assume that @marcosrmendezthd's suggestion worked out, so going to close this one. Thank you both for reporting/posting.
