### ISSUE TITLE
Adding ItemTextInput to show how variable are propaged

### ISSUE THREAD

**Issue by yo34** [relayjs/relay-examples#36]
Hello, 
 can you add an ItemTextInput in the TodoApp component to filter the todo list .
The goal of this request is to show how variables are used through fragment (ie variable set in the TodoApp and used in the TodoList).

Thank you.

**Comment by yuzhi** [comment]
Do you have any interest in contributing such component?

**Comment by yo34** [comment]
the documentation https://facebook.github.io/relay/docs/refetch-container.html explains how to code a Refetch Container but there is no full example that show how a parent fragment container set variables for this Refectch Container child.

**Comment by robrichard** [comment]
@yo34 I don't think it's possible for a parent fragment container to set variables for a child refetch container. If your parent component is handling events that required variables to change and new data to be fetched you should make that component a refetch container. As far as I know, it's only possible to change variables with QueryRenderers, refetch containers, or pagination containers.

**Comment by wincent** [comment]
@robrichard is correct.

> As far as I know, it's only possible to change variables with QueryRenderers, refetch containers, or pagination containers.

Technically, you can also put your own renderers or containers together (implementing some version of changing variables and refetching) by using the functionality exposed from the "relay-runtime" package, but whatever you build will most likely be pretty much equivalent to the provided renderer and containers.

Going to close this as the intent here is not to show how to do every possible thing in Relay, but instead replicate the ["standard" todomvc](http://todomvc.com/) interface using Relay.
