### ISSUE TITLE
Any reason to query `__typename` in `AddTodoMutation`?

### ISSUE THREAD

**Issue by joonhocho** [relayjs/relay-examples#55]
https://github.com/relayjs/relay-examples/blob/567ad0ff0c329a566369991d4e860c43df8c01d1/todo/js/mutations/AddTodoMutation.js#L23

Is this required for new edge or can be ignored?

**Comment by sibelius** [comment]
relay needs this to figure it out which node to update

**Comment by sibelius** [comment]
remember that relay modern does not do any query for you

you should describe the entirely query

**Comment by joonhocho** [comment]
Wouldn't id be enough to know which node to update?

**Comment by sibelius** [comment]
you need both, I guess

**Comment by joonhocho** [comment]
So the example should be fixed to have `id` as well?
I am asking because it means that I should start adding both `id` and `__typename` to all mutations queries.
With classic, I didn't specify it and had no problem.

**Comment by sibelius** [comment]
relay modern adds `id` to the query \o/

**Comment by joonhocho** [comment]
It seems only `id` is necessary and `__typename` is not. CLosing this issue.
