### ISSUE TITLE
How to access the client?

### ISSUE THREAD

**Issue by codemeasandwich** [relayjs/relay-examples#56]
Hi guys,

I have downloaded the source and installed from `relay-examples/todo/`

after running the commands I get:

    GraphQL Server is now running on http://localhost:8080
    Hash: d06d94fe6047259421f3
    Version: webpack 3.6.0

where do I go to see the "todo list app" ?
Thanks

**Comment by leebyron** [comment]
That's pretty weird. If you run `npm start` (or `yarn start`) You should see:

```
yarn start v1.0.0
$ babel-node ./server.js
GraphQL Server is now running on http://localhost:8080
App is now running on http://localhost:3000
```

At which point, you can open your browser to http://localhost:3000 to see the app.

**Comment by codemeasandwich** [comment]
Thanks. It was the post 300 I was missing :)

One thing. I am trying to trace the code to understand the flow. How do I enable source mapping?

Thanks
