### ISSUE TITLE
Any reason to query `cursor` in `AddTodoMutation`?

### ISSUE THREAD

**Issue by vafada** [relayjs/relay-examples#57]
https://github.com/relayjs/relay-examples/blob/0f6344fd8477db51c4aaad0b78e98f31a2c51da1/todo/js/mutations/AddTodoMutation.js#L24

Is this required for new edge or can be ignored?

Does the backend even need to generate a `cursor` field?

**Comment by steida** [comment]
@kassens Please. I have the same question.

**Comment by jstejada** [comment]
I might be wrong, but I believe we ask for the cursor for pagination. If we want to use the new element as the ancjhor for pagination, we'd need it's cursor. E.g. `(first: 10, after: <cursor>)`
