### ISSUE TITLE
WebSocket connection to 'ws://localhost:8734/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by moolo** [relayjs/relay-examples#58]
WebSocket connection to 'ws://localhost:8734/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by fernandocalsa** [comment]
Could you give us more information about this error?

**Comment by sibelius** [comment]
this is a problem when you have relay-devtools setup

**Comment by komali2** [comment]
I'm assuming this happens if you are working on a project that has relay-devtools included, but you don't have it installed as a chrome app lol. Nightmarish.

**Comment by komali2** [comment]
Holy god almighty, I had this issue come up again, google it, and find me a half year ago already flabbergasted at this oversight. And here I am in the same boat again lmao

**Comment by Stephen2** [comment]
This should be closed
