### ISSUE TITLE
Slightly more complex example with deeper routing

### ISSUE THREAD

**Issue by iamclaytonray** [relayjs/relay-examples#59]
Feature Request:

I'd love to see a more realistic example using Relay Modern & React & GraphQL. Routing with Relay can be a pain and I haven't found a decent example so far. I think something like a full CRUD example for a blog would be good enough. That's enough routing to at least get started. I can submit a PR and at least do the React portion. From there, I'm kind of lost. (Something that I've heard a lot of other devs struggle with as well.) Thoughts? I'm open to discussing this and to dedicate some time to writing a really good example to add to the collection.

Update:

A good example that I haven't seen before is to get a single resource. So, I hit `demo.com/posts/1` and get the blog post I clicked on from `demo.com/posts`.

**Comment by steida** [comment]
Check example I made for Next.js https://github.com/zeit/next.js/tree/master/examples/with-relay-modern
