### ISSUE TITLE
Electron app to debug Relay

### ISSUE THREAD

**Issue by fernandocalsa** [relayjs/relay-examples#61]
Hi! I don't know if this is the best place to ask this.

I was reading Relay documentation, and in this URL [https://facebook.github.io/relay/docs/relay-debugging.html](https://facebook.github.io/relay/docs/relay-debugging.html) appears an "Electron app" to debug React Native apps, but the project that is linked is removed. I would like to know if this app is still working, and if you could fix that link.

Thank you for your help

**Comment by yuzhi** [comment]
Closing as this refers to out dated documentation .
