### ISSUE TITLE
WebSocket connection to 'ws://0.0.0.0:8070/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by alandwiprasetyo** [relayjs/relay-examples#64]
Hi, i have some problem when deploy on production, I have error in my console

`WebSocket connection to 'ws://0.0.0.0:8070/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

Thank for helping me

**Comment by jaivintricore** [comment]
@alandwiprasetyo were you able to resolve this issue?
