### ISSUE TITLE
Uncaught Error: RelayModernGraphQLTag: Expected a request, got .. 

### ISSUE THREAD

**Issue by jamesmbowler** [relayjs/relay-examples#82]
I just tried this, after I saw that the relay version was upped to 1.7, and started getting this error:

> Uncaught Error: RelayModernGraphQLTag: Expected a request, got `{"fragment":{"argumentDefinitions": ...

and 

> The above error occurred in the <ReactRelayQueryRenderer> component:
>     in ReactRelayQueryRenderer

This was working, last time I had checked, before the most recent commit.

**Comment by Stephen2** [comment]
Can't replicate, probably fixed since opening, and definitely fixed since upgrading to 2.0.0
