### ISSUE TITLE
TodoMVC need to use react-native 0.33

### ISSUE THREAD

**Issue by thienpow** [relayjs/relay-examples#9]
package.json need to update to use react-native 0.33, else it won't build

**Comment by thienpow** [comment]
below also need to be updated to the latest version, else it won't run.

    "babel-relay-plugin": "0.9.3",
    "react": "15.3.2",
    "react-native": "0.33.0",
    "react-relay": "0.9.3"

**Comment by Lenin7** [comment]
Do you have the list of all changes required to make this app work with 0.33?
Thanks
